Game spec
Lidya1234/Tic_tac_toe_test pull request #2
Opened 2020-10-14 14:38 UTC by Adewunmi97

-Added games_spec file
-Added RSpec test cases for different methods

2020-10-14 16:58 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello @Lidya1234 and @Adewunmi97!

Good job so far with this project! 👏 
But we have to make some changes before getting approved! 💪 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review
Good luck! 😃 

## Mandatory changes
- Your linters are failing, kindly make them all pass
- One of your tests is failing, kindly make it pass.
   - RSpec ./spec/games_spec.rb:32 # game method tests Validates position
- Add test section in your readme file
- You must do tests for all your public methods, there are still methods without a test, kindly add those tests

2020-10-15 13:59 UTC, moinkhanif approved these changes
##  Status: Approved! 🥳  

Hey team, great work on your project ✨. You have completed the requested changes by the previous TSE. Therefore **I am approving** your project. 🎉
However, please do checkout the optional changes I have requested below:
- Please add negative tests as well. Having both positive and negative tests makes sure the project is running as expected.
- The rest are commented below.

You may now merge the branch. Hope you enjoy upcoming projects and understand the concepts better! 😄

Happy coding! 🐱‍🏍

2020-10-15 13:59 UTC, moinkhanif commented on README.md
[OPTIONAL] Add test screenshot within a test heading.

2020-10-15 13:59 UTC, moinkhanif commented on bin/main
> +
[OPTIONAL]  But important, rename main to main.rb

2020-10-15 14:59 UTC, merged